### ISSUE TITLE
Please add support for Swift Package Manager

### ISSUE THREAD

**Issue by salling** [kantarsifo/kantar-sifo-mobile-analytics-pod#1]
I have collected some info and links to make this easier for you.

----

DISTRIBUTING BINARY AS PART OF SWIFT PACKAGE

In order to make a closed-source binary available through Swift Package Manager, it needs to be wrapped in an xcframework.

NOTE: an xcframework may wrap both dynamic frameworks and static libraries (incl header files). Static library may be preferable, b/c it allows for speedier launch performance.

Here's Apple's documentation on how to create an xcframework:
https://help.apple.com/xcode/mac/11.4/#/dev544efab96

Here's Apple's documentation on how to package binaries in a Swift package:
https://developer.apple.com/documentation/swift_packages/distributing_binary_frameworks_as_swift_packages

Regardless of whether your package contains a static library or dynamic framework, there are SPM bugs to be aware of.

AS STATIC LIBRARY

Here's an example of a package where a static library has been included:
https://github.com/Appboy/appboy-ios-sdk/blob/master/Package.swift

Note: A bug in SPM re: static libraries necessitates some post-build cleanup:
https://github.com/Appboy/appboy-ios-sdk/releases/tag/3.29.0

AS DYNAMIC FRAMEWORK

When a dynamic framework is wrapped in xcframework and distributed in a Swift package, another SPM bug results in code signing issue:
https://bugs.swift.org/browse/SR-13343

Here's a workaround:
https://pspdfkit.com/guides/ios/current/knowledge-base/library-not-found-swiftpm/

**Comment by salling** [comment]
@jnutting Do you think SPM support could happen?

This library is one of two remaining dependencies that we consume in our project, and the other one has SPM support on the road map.

🙇

**Comment by lizell** [comment]
This is also fixed in the "internal" version. Hopefully it could be released to everyone as soon as possible.

**Comment by salling** [comment]
I'll close this issue, as Swift Package Manager support has indeed been released, albeit in a different repository. 

https://github.com/kantarsifo/SifoInternet_IOS_SDK
