### ISSUE TITLE
Consumer of SDK needs to be in control re: when to ask for tracking permission

### ISSUE THREAD

**Issue by salling** [kantarsifo/kantar-sifo-mobile-analytics-pod#2]
I notice that in the latest version of your SDK, it "now asks for tracking permission on iOS 14 for panelists". Perhaps I'm misunderstanding this release note, but in our usage of your SDK, it's crucially important that *we* are in control of when to ask the user whether we have permission to track.

**Comment by peteranderssonkantar** [comment]
Thank you for your feedback. You are right, the Sifo SDK should not ask for ATT permissions – that is up to the host of the app, eg you, to decide. As of v5.0.4 (released today November 26th 2020) the Sifo SDK no longer uses AppTrackingTransparency framework. The Sifo SDK will adapt to whatever permissions the host app gets from the end user
